### ISSUE TITLE
spelling mistake

### ISSUE THREAD

**Issue by kingmt** [BSData/aeronautica-imperialis#51] opened 2021-12-18 18:22 UTC
Aircraft is misspelled as Aircarft. This is seen in the ros file XML and in the popup descriptions

**Comment by zopha** [comment] 2021-12-20 12:17
Found in profile type, "Aricarft Upgrades" where everything else is branching from. I've fixed this root cause and it appears to be fine in the roster editor although it lingers on in the XML.

![image](https://user-images.githubusercontent.com/1666415/146765779-f9c898f1-6341-4001-8815-2da7be7c0d2c.png)

**Comment by kingmt** [comment] 2021-12-20 16:19
Thanks for the quick response I was actually going to make this change today and open a pull request, but you beat me to it. I will still dig into the XML generation to see if I can find the issue there.

One other thing, my version of the data file is still version 1.6.3 dated November 11th. Has this fix been published as a new version and I am just not getting it?

**Comment by zopha** [comment] 2021-12-20 16:30
Sorry, I didn't realise. I've had battlescribe on my mind the last few days so made some time for it today.

It's live in the master branch but a release needs to be pushed out before it's live on appspot. If you use the "Gallary" option you should get it sooner, if you use iOS then the only option you have is the legacy system via Appspot. More info here - https://github.com/BSData/wh40k/issues/1706

You can download the files manually, delete the .catz files and stick the .cat files in the folder. I'll draft and push a release soon but that will still take up to 12 hours to appear on appspot.

**Comment by zopha** [comment] 2022-01-04 21:51
I'll close this off now as the additonal issue of an old release was resovled when I publised updated files.

**Closed by zopha** 2022-01-04 21:51 UTC
Labels: bug
